#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {D:/Facultad ITBA/Ano 5/Cuatrimestre 1/E4/TPs-G1_E4/TP3/Laticce/8bits/test_pablo/promote.xml}
msg_load {D:/Facultad ITBA/Ano 5/Cuatrimestre 1/E4/TPs-G1_E4/TP3/Laticce/8bits/test_pablo/promote.xml}
des_set_project_udb -in {test_pablo_test_pablo_syn.udb} -out {test_pablo_test_pablo_map.udb} -milestone map -pm ice40tp
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false}
map_run

} out]} {
   runtime_log $out
   set ret 1
}
exit -force ${ret}
