#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/valen/Downloads/UPduino-v3.0-master/RTL/radiant-reveal/TP3_E4/promote.xml}
msg_load {C:/Users/valen/Downloads/UPduino-v3.0-master/RTL/radiant-reveal/TP3_E4/promote.xml}
des_set_project_udb -in {TP3_E4_TP3_E4_syn.udb} -out {TP3_E4_TP3_E4_map.udb} -milestone map -pm ice40tp
map_set_option {pdc_file "C:/Users/valen/Downloads/UPduino-v3.0-master/RTL/radiant-reveal/TP3_E4/source/TP3_E4/TP3_E4.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false}
map_run

} out]} {
   runtime_log $out
   set ret 1
}
exit -force ${ret}
