

// TOOL:     vlog2tf
// DATE:     Fri Jun  7 21:45:08 2024
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   main
// DESIGN:   main
// FILENAME: main_tf.v
// PROJECT:  TP3_E4
// VERSION:  2.0
// This file is auto generated by Radiant


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module main_tf();

// Inputs
    reg clk;


// Outputs
    wire Va;
    wire Van;
    wire Vb;
    wire Vbn;
    wire Vc;
    wire Vcn;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    main UUT (
        .clk(clk), 
        .Va(Va), 
        .Van(Van), 
        .Vb(Vb), 
        .Vbn(Vbn), 
        .Vc(Vc), 
        .Vcn(Vcn)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            clk = 0;
    end

endmodule // main_tf